# Generated by Django 4.2.8 on 2023-12-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribute',
            name='enable_comments',
            field=models.BooleanField(default=True),
        ),
    ]
