# Generated by Django 4.2.8 on 2023-12-29 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tributes', '0002_tribute_enable_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(blank=True, max_length=3000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tributes.tribute')),
            ],
        ),
    ]
