# Generated by Django 4.2.8 on 2024-01-12 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributes', '0003_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribute',
            name='picture',
            field=models.ImageField(blank=True, help_text='Images must be equal to or less than 5MB. Allowed file types: jpg, jpeg.', null=True, upload_to='pictures', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg'])]),
        ),
    ]
