# Generated by Django 4.2.8 on 2024-01-15 20:58

import django.core.validators
from django.db import migrations, models
import tributes.models


class Migration(migrations.Migration):

    dependencies = [
        ('tributes', '0004_tribute_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribute',
            name='picture',
            field=models.ImageField(blank=True, help_text='Images must be equal to or less than 5MB. Allowed file types: jpg, jpeg.', null=True, upload_to=tributes.models.upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg'])]),
        ),
    ]
